parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        \Symfony\Component\Console\Command\Command:
            tags: [ 'console.command' ]

    Ebln\PolyphonicComposing\:
        resource: 'src/*'
        exclude:
            - 'src/*/Contract/*'
            - 'src/Symbiont/*'
