parameters:
    dummy.parameter: "FOOBAR"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ebln\ParasiteDemo\Endobiont\:
        resource: 'src/*'

    # RAVELIN IN EXOBIOANTIC ROOT
    Ebln\ParasiteDemo\Ravelin\Transceiver\:
        resource: '../src/Ravelin/Transceiver/*'

    # ENTRY POINT
    Ebln\ParasiteDemo\Endobiont\EndobionticService:
        public: true
